name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: debian-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./nikav/ root@$SERVER_IP:/var/www/html/racunalnistvo-v-oblaku/
          ssh -i key.pem -o StrictHostKeyChecking=no root@$SERVER_IP "chown -R www-data:www-data /var/www/html/racunalnistvo-v-oblaku/nikav && systemctl restart apache2"
